# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_auto_20171115_0710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(default='United Kingdom', max_length=255)),
                ('city', models.CharField(default='London', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.AgeGroup')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
