# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20171115_0710'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='players.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='side_players',
            field=models.ManyToManyField(blank=True, null=True, related_name='side_players', to='players.Player'),
        ),
    ]
